# Copyright © 2021 Cask Data, Inc.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# This workflow will deploy a build
name: Deploy

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: k8s-runner-cloudbuild
    steps:
    - id: gcloud
      uses: google-github-actions/setup-gcloud@master

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Cancel previous builds
      run: >
        gcloud builds list
        --project=cloud-data-fusion-builds
        --filter="buildTriggerId:e2d27f65-685a-457b-a66f-b686f3a1218d
        AND substitutions._BRANCH_REPLACEMENT:${{ steps.extract_branch.outputs.branch }}"
        --format="value(id)"
        --ongoing
        | xargs -n 1 gcloud builds cancel --project cloud-data-fusion-builds

    - name: Start build
      id: start_build
      run: >
        echo "##[set-output name=build;]$(
        curl -L -X POST 'https://cloudbuild.googleapis.com/v1/projects/cloud-data-fusion-builds/triggers/e2d27f65-685a-457b-a66f-b686f3a1218d:run'
        -H "Authorization: Bearer $(gcloud auth print-access-token)"
        -H 'Content-Type: application/json' --data-raw '{
            "substitutions": {
                "_UPSTREAM_BRANCH_NAME": "develop",
                "_CDAP_MINOR_VERSION_MVN": "6.5",
                "_SOURCE": "github",
                "_REMOTE_UPDATE": "true",
                "_BRANCH_REPLACEMENT": "${{ steps.extract_branch.outputs.branch }}"
            },
            "branchName": "speedup"
        }') | jq -r .metadata.build.id"

    - name: Wait for build
      run: >
        gcloud builds log --project cloud-data-fusion-builds --stream ${{ steps.start_build.outputs.build }}
